// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeatroAPI.Data;

#nullable disable

namespace TeatroAPI.Data.Migrations
{
    [DbContext(typeof(TeatroAPIContext))]
    [Migration("20240320105044_MigracionInicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeatroAPI.Model.Funcion", b =>
                {
                    b.Property<int>("FuncionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FuncionID"));

                    b.Property<DateTime?>("FechaHora")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int?>("ObraID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Precio")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("SalaID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("FuncionID");

                    b.HasIndex("ObraID");

                    b.HasIndex("SalaID");

                    b.ToTable("Funciones");

                    b.HasData(
                        new
                        {
                            FuncionID = 1,
                            FechaHora = new DateTime(2024, 3, 26, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            ObraID = 3,
                            Precio = 15,
                            SalaID = 1
                        },
                        new
                        {
                            FuncionID = 2,
                            FechaHora = new DateTime(2024, 3, 27, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            ObraID = 5,
                            Precio = 25,
                            SalaID = 2
                        },
                        new
                        {
                            FuncionID = 3,
                            FechaHora = new DateTime(2024, 3, 28, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            ObraID = 2,
                            Precio = 18,
                            SalaID = 1
                        },
                        new
                        {
                            FuncionID = 4,
                            FechaHora = new DateTime(2024, 3, 29, 22, 15, 0, 0, DateTimeKind.Unspecified),
                            ObraID = 8,
                            Precio = 20,
                            SalaID = 2
                        },
                        new
                        {
                            FuncionID = 5,
                            FechaHora = new DateTime(2024, 3, 30, 19, 45, 0, 0, DateTimeKind.Unspecified),
                            ObraID = 1,
                            Precio = 10,
                            SalaID = 1
                        },
                        new
                        {
                            FuncionID = 6,
                            FechaHora = new DateTime(2024, 3, 31, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            ObraID = 4,
                            Precio = 29,
                            SalaID = 2
                        },
                        new
                        {
                            FuncionID = 7,
                            FechaHora = new DateTime(2024, 4, 1, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            ObraID = 6,
                            Precio = 22,
                            SalaID = 1
                        },
                        new
                        {
                            FuncionID = 8,
                            FechaHora = new DateTime(2024, 3, 26, 22, 30, 0, 0, DateTimeKind.Unspecified),
                            ObraID = 7,
                            Precio = 14,
                            SalaID = 2
                        },
                        new
                        {
                            FuncionID = 9,
                            FechaHora = new DateTime(2024, 3, 27, 19, 15, 0, 0, DateTimeKind.Unspecified),
                            ObraID = 3,
                            Precio = 17,
                            SalaID = 1
                        },
                        new
                        {
                            FuncionID = 10,
                            FechaHora = new DateTime(2024, 3, 28, 21, 45, 0, 0, DateTimeKind.Unspecified),
                            ObraID = 5,
                            Precio = 26,
                            SalaID = 2
                        },
                        new
                        {
                            FuncionID = 11,
                            FechaHora = new DateTime(2024, 3, 29, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            ObraID = 1,
                            Precio = 12,
                            SalaID = 1
                        },
                        new
                        {
                            FuncionID = 12,
                            FechaHora = new DateTime(2024, 3, 30, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            ObraID = 8,
                            Precio = 27,
                            SalaID = 2
                        },
                        new
                        {
                            FuncionID = 13,
                            FechaHora = new DateTime(2024, 3, 31, 20, 15, 0, 0, DateTimeKind.Unspecified),
                            ObraID = 2,
                            Precio = 16,
                            SalaID = 1
                        },
                        new
                        {
                            FuncionID = 14,
                            FechaHora = new DateTime(2024, 4, 1, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            ObraID = 4,
                            Precio = 30,
                            SalaID = 2
                        },
                        new
                        {
                            FuncionID = 15,
                            FechaHora = new DateTime(2024, 3, 26, 21, 30, 0, 0, DateTimeKind.Unspecified),
                            ObraID = 7,
                            Precio = 13,
                            SalaID = 1
                        },
                        new
                        {
                            FuncionID = 16,
                            FechaHora = new DateTime(2024, 3, 27, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            ObraID = 6,
                            Precio = 24,
                            SalaID = 2
                        },
                        new
                        {
                            FuncionID = 17,
                            FechaHora = new DateTime(2024, 3, 28, 19, 45, 0, 0, DateTimeKind.Unspecified),
                            ObraID = 3,
                            Precio = 11,
                            SalaID = 1
                        },
                        new
                        {
                            FuncionID = 18,
                            FechaHora = new DateTime(2024, 3, 29, 21, 15, 0, 0, DateTimeKind.Unspecified),
                            ObraID = 5,
                            Precio = 28,
                            SalaID = 2
                        },
                        new
                        {
                            FuncionID = 19,
                            FechaHora = new DateTime(2024, 3, 30, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            ObraID = 1,
                            Precio = 14,
                            SalaID = 1
                        },
                        new
                        {
                            FuncionID = 20,
                            FechaHora = new DateTime(2024, 3, 31, 22, 45, 0, 0, DateTimeKind.Unspecified),
                            ObraID = 8,
                            Precio = 19,
                            SalaID = 2
                        },
                        new
                        {
                            FuncionID = 21,
                            FechaHora = new DateTime(2024, 4, 1, 19, 15, 0, 0, DateTimeKind.Unspecified),
                            ObraID = 2,
                            Precio = 23,
                            SalaID = 1
                        },
                        new
                        {
                            FuncionID = 22,
                            FechaHora = new DateTime(2024, 3, 26, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            ObraID = 7,
                            Precio = 17,
                            SalaID = 2
                        },
                        new
                        {
                            FuncionID = 23,
                            FechaHora = new DateTime(2024, 3, 27, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            ObraID = 4,
                            Precio = 40,
                            SalaID = 1
                        },
                        new
                        {
                            FuncionID = 24,
                            FechaHora = new DateTime(2024, 3, 28, 22, 30, 0, 0, DateTimeKind.Unspecified),
                            ObraID = 6,
                            Precio = 25,
                            SalaID = 2
                        });
                });

            modelBuilder.Entity("TeatroAPI.Model.Obra", b =>
                {
                    b.Property<int>("ObraID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObraID"));

                    b.Property<int>("CategoriaID")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ObraID");

                    b.ToTable("Obras");

                    b.HasData(
                        new
                        {
                            ObraID = 1,
                            CategoriaID = 1,
                            Descripcion = "¿Hasta que punto nos somete la tecnología? ¿Somos libres? ¿Qué tipo de sociedad hemos construido entre todos? ¿Cómo se nos plantea el futuro? ¿Nos merecemos el calificativo de \"seres humanos\"? \r\n\r\nAdictos trata de dar respuesta a estos interrogantes que abordan problemáticas que nos afectan a todos. Cuestiones que no acostumbramos a ver subidas en un escenario que ahora se confrontan con el público contemporáneo. \r\n\r\nLas personas solemos asumir ciertos paradigmas y cuestiones como válidos y ciertos sin siquiera plantearnos las mentiras y distorsiones que pueden esconder detrás. En un mundo en el que la desinformación se expande, el personaje de Estela y su transformación constituirá una metáfora de la disposición del ser humano para cambiar de actitud. Un texto que reivindica y reflexiona sobre la capacidad de reacción de las personas y que enseña que un punto de rebeldía es necesario cuando queremos cambiar algo. \r\n\r\nLola Herrera, Ana Labordeta y Lola Baldrich protagonizan un espectáculo que grita... ¡Adictos somos todos!",
                            Imagen = "https://cd1.taquilla.com/data/images/t/de/adictos-con-lola-herrera__330x275.jpg",
                            Titulo = "Adictos con Lola Herrera"
                        },
                        new
                        {
                            ObraID = 2,
                            CategoriaID = 1,
                            Descripcion = "Mentiras, verdades, ilusiones y la educación que recibimos desde pequeños... \r\n\r\nLaponia es una comedia de Cristina Clemente y Marc Angelet que convierte una velada de fiesta e ilusión en una batalla entre hermanas, parejas y cuñados. Una obra que nos hará pensar y reír a la vez que nos planteará diferentes situaciones éticas y morales que nos podrían pasar a todos. ¿La verdad es tan buena como dicen y la mentira tan mala?\r\n\r\nLaponia es el lugar en el que dos familias se encuentran con la intención de celebrar la Nochebuena y la llegada de Papá Noel. Todo parece ir bien hasta que una de las criaturas explica al otro que Papá Noel no existe, y que es un personaje que ha sido creado para que los padres puedan controlar a sus hijos y hacer que se comporten bien.\r\n\r\nA partir de aquí, las dos parejas se enzarzan en una discusión sobre la verdad y la mentira, las costumbres y los valores familiares, y comienzan a salir a la luz varias verdades ocultas. ¿Qué secreto inconfesable tiene cada uno de ellos? ¡Descúbrelo tú mismo!",
                            Imagen = "https://cd1.taquilla.com/data/images/t/8e/laponia__330x275.jpg",
                            Titulo = "Laponia"
                        },
                        new
                        {
                            ObraID = 3,
                            CategoriaID = 0,
                            Descripcion = "Tras el éxito cosechado con La Gran Ilusión, uno de los mayores espectáculos de magia de nuestro país, el Mago Pop llega de nuevo para mostrarnos los mejores trucos de ilusionismo en su nuevo espectáculo Nada es imposible. Y es que es innegable que Antonio Díaz ha sabido sacarle partido a lo que mejor sabe hacer, y no ha dudado en demostrar que el arte de la magia puede ser exhibido tanto en los teatros como en televisión.\r\n\r\nNada es Imposible es un espectáculo en el que magia y humor se fusionan para hacernos pasar una velada de lo más original. Con el único objetivo de sorprender al público, este experto en magia ha preparado entre un gran secretismo  unos de sus shows más creativos hasta el momento, en el que no dudará en hacer uso de la innovación y la fantasía. Antonio Díaz nos invita a un así a hacer un recorrido por lo extraordinario, donde el asombro, la diversión y las sorpresas no terminarán nunca.\r\n\r\nLa historia de Antonio Díaz es la historia de la sorpresa, de la ilusión. De la pequeña pantalla pasó al teatro, para convertirse en el mago más taquillero de toda Europa. Conocido internacionalmente, este Premio Nacional de Magia llega dispuesto a repetir el éxito de sus anteriores espectáculos y demostrarnos que verdaderamente, nada es imposible.",
                            Imagen = "https://cd1.taquilla.com/data/images/t/78/nada-es-imposible-el-mago-pop__330x275.jpg",
                            Titulo = "Nada es Imposible - el Mago pop"
                        },
                        new
                        {
                            ObraID = 4,
                            CategoriaID = 2,
                            Descripcion = "Cristina Clemente y Marc Angelet son los autores de 'Una Terapia Integral', la comedia que trata de retratar a una sociedad que parece estar eliminando la religión, pero que a su vez tiene una gran necesidad de creer, tener fe en algo que nos ayude a encontrar sentido a nuestras vidas y a poner orden en ellas. Un curso intensivo con cuatro magníficos intérpretes Antonio Molero, Angy Fernández, Esther Ortega y César Camino.\r\n\r\n¿Una corteza poco crujiente? Problemas laborales ¿Una miga demasiado densa? Crisis de pareja ¿Un pan soso? Una vida sexual insatisfactoria.\r\n\r\nTodos quieren apuntarse a los cursos de hacer pan que imparte Toni Roca. Sus diez años de experiencia y las pocas plazas ofertadas hacen que la gente haga cola para apuntarse. Para el maestro, \"somos el pan que hacemos\" y su curso garantiza que, después de unas cuantas sesiones, el alumno será capaz de hacer un pan excelente. Lo curioso de su sistema de aprendizaje es que los alumnos no solo tendrán que amasar o controlar la temperatura del horno: también deberán sincerarse, llorar, reír, gritar... y liberarse. \r\n\r\nToni Roca tiene clara su premisa: “Para hacer un buen pan, no hace falta la mejor harina o la levadura más fresca, para hacer un buen pan solo es necesario estar bien con uno mismo”. ",
                            Imagen = "https://cd1.taquilla.com/data/images/t/18/una-terapia-integral-madrid__330x275.jpg",
                            Titulo = "Una Terapia Integral Madrid"
                        },
                        new
                        {
                            ObraID = 5,
                            CategoriaID = 2,
                            Descripcion = "Lola es una camarera Sevillana, cansada, frustrada y enfadada con la vida. Periodista frustrada y portadora de la mala suerte, aguanta cada día a los borrachos del trabajo con resignación y todo el sentido del humor que puede. Sin embargo, de tanto recordar su mala suerte y de tanto blasfemar, un día en un arrebato se acuerda hasta de la mísmisima virgen.\r\n\r\nHasta que La Virgen se le aparece. Y descubre que no son mujeres tan diferentes.\r\n\r\nEsta comedia arrolladora e incesante es un auténtico símbolo del teatro de humor en nuestro país: más de diez años de programación a sus espaldas lo corroboran. Interpretada por Lola Marmolejo en el papel de La Virgen y Rocío Galán como camarera, de la compañía Bastarda Española, es una apuesta segura si lo que estás buscando es una tarde de carcajadas.\r\n\r\n¡No te la pierdas!",
                            Imagen = "https://cd1.taquilla.com/data/images/t/f8/estrella-sublime__330x275.jpeg",
                            Titulo = "Estrella Sublime"
                        },
                        new
                        {
                            ObraID = 6,
                            CategoriaID = 1,
                            Descripcion = "Una compañía de teatro amateur quiere presentar al público su primera obra: una función de misterio al más puro estilo Agatha Christie, y estamos todos invitados. Sin embargo, montar un gran espectáculo es más complicado, y todo lo que podría salir mal parece que hoy está dispuesto a fallar.\r\n\r\nY es que los actores que hacen de muertos se mueven más de lo debido, el atrezzo se cae a cachos, el guión se les olvida, la dirección es un desastre, la iluminación falla... Una consecución de desaciertos que convierten el estreno en una hilarante comedia con reminiscencias al estilo Monthy Python.\r\n\r\nLa función que sale mal ha hecho partirse de risa a más de 8 millones de espectadores desde su estreno en el West End en Londres (2012), acumulando los mayores premios en su categoría, y sigue agotando localidades cada día. También ha triunfado en Broadway y ha sido presentada en 30 países. ¡Ahora puedes disfrutar de ella en Madrid!",
                            Imagen = "https://cd1.taquilla.com/data/images/t/3d/la-funcion-que-sale-mal__330x275.jpg",
                            Titulo = "La Función que Sale mal"
                        },
                        new
                        {
                            ObraID = 7,
                            CategoriaID = 0,
                            Descripcion = "Norma Aleandro dirige Escenas de la vida conyugal, una versión teatral de la película homónima de Ingmar Bergman, que desde su presentación cosechó varios e importantísimos premios como el Golden Globe y el BAFTA. En 1981, Bergman estrenó la primera adaptación teatral en el teatro Marstall de Munich (Alemania) y desde entonces ha sido un éxito en numerosos países.\r\n\r\nRicardo Darín y Andrea Pietra dan vida respectivamente a Juan y Marina, una pareja que representa sobre el escenario momentos clave en su matrimonio. A lo largo de la obra, se exploran temas como el amor, la comunicación, la infidelidad, la rutina y el paso del tiempo. La historia sigue la evolución de la relación desde los primeros días de amor apasionado hasta las dificultades y desafíos que enfrenta la pareja a medida que transcurren los años.\r\n\r\nLa narrativa atemporal y la sinergia entre actores y personajes rompen la cuarta pared, sumergiendo a la audiencia en un juego emotivo y reflexivo sobre el matrimonio y la vida: situaciones aparentemente divertidas que dentro ocultan un profundo dramatismo. Escenas de la vida conyugal ha sido elogiada por su profundidad psicológica y su capacidad para conectar con el público a través de la identificación con los personajes. Así, ha recibido 4 premios Estrella de Mar y el prestigioso Premio José María Vilches, una distinción que honra a las obras que destacan por su contribución a la dignidad humana y los valores sociales.",
                            Imagen = "https://cd1.taquilla.com/data/images/t/c5/escenas-de-la-vida-conyugal__330x275.jpg",
                            Titulo = "Escenas de la Vida Conyugal"
                        },
                        new
                        {
                            ObraID = 8,
                            CategoriaID = 0,
                            Descripcion = "Rafael Álvarez es un actor y dramaturgo español de origen cordobés, más conocido por su sobrenombre artístico El Brujo.\r\n\r\nTitulado por la Real Escuela Superior de Arte Dramático, su actividad comenzó cuando tenía sólo 20 años con el \"El juego de los Insectos\", estrenada en 1970. Desde entonces, Rafael Álvarez se ha dedicado a la actuación, la producción y el mundo del teatro en general.\r\n\r\nEn 1988 funda la compañía Pentación S.A. junto a nombres como José Luis Alonso de Santos, Gerardo Malla y  Jesús Cimarro, y también su propia productora, El Brujo, S.L., cuyas obras se mantienen programadas con mucha asiduidad.\r\n\r\nEste actor y productor también ha participado en diversas películas (Juncal, Brigada Central...) y ha recibido premios tan destacados como el Premio Canal Sur al Mejor Espectáculo teatral 2000 y XIII Premio Nacional de Teatro Pepe Isbert, entre muchos otros.",
                            Imagen = "https://cd1.taquilla.com/data/images/t/0f/el-brujo-rafael-alvarez__330x275.jpg",
                            Titulo = "Rafael Álvarez, El Brujo"
                        });
                });

            modelBuilder.Entity("TeatroAPI.Model.Reserva", b =>
                {
                    b.Property<int>("ReservaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservaID"));

                    b.Property<int>("Asiento")
                        .HasColumnType("int");

                    b.Property<int>("FuncionID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ReservaID");

                    b.HasIndex("FuncionID");

                    b.HasIndex("UserID");

                    b.ToTable("Reservas");

                    b.HasData(
                        new
                        {
                            ReservaID = 1,
                            Asiento = 2,
                            FuncionID = 5,
                            UserID = 34
                        },
                        new
                        {
                            ReservaID = 2,
                            Asiento = 45,
                            FuncionID = 1,
                            UserID = 87
                        },
                        new
                        {
                            ReservaID = 3,
                            Asiento = 32,
                            FuncionID = 15,
                            UserID = 56
                        },
                        new
                        {
                            ReservaID = 4,
                            Asiento = 18,
                            FuncionID = 8,
                            UserID = 22
                        },
                        new
                        {
                            ReservaID = 5,
                            Asiento = 50,
                            FuncionID = 24,
                            UserID = 3
                        },
                        new
                        {
                            ReservaID = 6,
                            Asiento = 5,
                            FuncionID = 13,
                            UserID = 77
                        },
                        new
                        {
                            ReservaID = 7,
                            Asiento = 27,
                            FuncionID = 7,
                            UserID = 15
                        },
                        new
                        {
                            ReservaID = 8,
                            Asiento = 11,
                            FuncionID = 19,
                            UserID = 89
                        },
                        new
                        {
                            ReservaID = 9,
                            Asiento = 40,
                            FuncionID = 2,
                            UserID = 47
                        },
                        new
                        {
                            ReservaID = 10,
                            Asiento = 29,
                            FuncionID = 22,
                            UserID = 9
                        },
                        new
                        {
                            ReservaID = 11,
                            Asiento = 15,
                            FuncionID = 10,
                            UserID = 67
                        },
                        new
                        {
                            ReservaID = 12,
                            Asiento = 36,
                            FuncionID = 4,
                            UserID = 98
                        },
                        new
                        {
                            ReservaID = 13,
                            Asiento = 22,
                            FuncionID = 11,
                            UserID = 52
                        },
                        new
                        {
                            ReservaID = 14,
                            Asiento = 48,
                            FuncionID = 6,
                            UserID = 33
                        },
                        new
                        {
                            ReservaID = 15,
                            Asiento = 14,
                            FuncionID = 16,
                            UserID = 41
                        },
                        new
                        {
                            ReservaID = 16,
                            Asiento = 31,
                            FuncionID = 14,
                            UserID = 29
                        },
                        new
                        {
                            ReservaID = 17,
                            Asiento = 9,
                            FuncionID = 21,
                            UserID = 72
                        },
                        new
                        {
                            ReservaID = 18,
                            Asiento = 23,
                            FuncionID = 9,
                            UserID = 18
                        },
                        new
                        {
                            ReservaID = 19,
                            Asiento = 47,
                            FuncionID = 3,
                            UserID = 64
                        },
                        new
                        {
                            ReservaID = 20,
                            Asiento = 28,
                            FuncionID = 17,
                            UserID = 55
                        },
                        new
                        {
                            ReservaID = 21,
                            Asiento = 8,
                            FuncionID = 23,
                            UserID = 46
                        },
                        new
                        {
                            ReservaID = 22,
                            Asiento = 33,
                            FuncionID = 18,
                            UserID = 19
                        },
                        new
                        {
                            ReservaID = 23,
                            Asiento = 12,
                            FuncionID = 20,
                            UserID = 85
                        },
                        new
                        {
                            ReservaID = 24,
                            Asiento = 38,
                            FuncionID = 12,
                            UserID = 74
                        },
                        new
                        {
                            ReservaID = 25,
                            Asiento = 21,
                            FuncionID = 5,
                            UserID = 63
                        },
                        new
                        {
                            ReservaID = 26,
                            Asiento = 6,
                            FuncionID = 8,
                            UserID = 27
                        },
                        new
                        {
                            ReservaID = 27,
                            Asiento = 49,
                            FuncionID = 16,
                            UserID = 39
                        },
                        new
                        {
                            ReservaID = 28,
                            Asiento = 34,
                            FuncionID = 24,
                            UserID = 10
                        },
                        new
                        {
                            ReservaID = 29,
                            Asiento = 7,
                            FuncionID = 13,
                            UserID = 91
                        },
                        new
                        {
                            ReservaID = 30,
                            Asiento = 26,
                            FuncionID = 11,
                            UserID = 58
                        },
                        new
                        {
                            ReservaID = 31,
                            Asiento = 19,
                            FuncionID = 9,
                            UserID = 17
                        },
                        new
                        {
                            ReservaID = 32,
                            Asiento = 44,
                            FuncionID = 20,
                            UserID = 80
                        },
                        new
                        {
                            ReservaID = 33,
                            Asiento = 3,
                            FuncionID = 2,
                            UserID = 42
                        },
                        new
                        {
                            ReservaID = 34,
                            Asiento = 37,
                            FuncionID = 17,
                            UserID = 24
                        },
                        new
                        {
                            ReservaID = 35,
                            Asiento = 16,
                            FuncionID = 6,
                            UserID = 79
                        },
                        new
                        {
                            ReservaID = 36,
                            Asiento = 30,
                            FuncionID = 21,
                            UserID = 95
                        },
                        new
                        {
                            ReservaID = 37,
                            Asiento = 43,
                            FuncionID = 15,
                            UserID = 68
                        },
                        new
                        {
                            ReservaID = 38,
                            Asiento = 24,
                            FuncionID = 10,
                            UserID = 60
                        },
                        new
                        {
                            ReservaID = 39,
                            Asiento = 10,
                            FuncionID = 7,
                            UserID = 36
                        },
                        new
                        {
                            ReservaID = 40,
                            Asiento = 35,
                            FuncionID = 14,
                            UserID = 83
                        },
                        new
                        {
                            ReservaID = 41,
                            Asiento = 46,
                            FuncionID = 3,
                            UserID = 50
                        },
                        new
                        {
                            ReservaID = 42,
                            Asiento = 1,
                            FuncionID = 19,
                            UserID = 13
                        },
                        new
                        {
                            ReservaID = 43,
                            Asiento = 4,
                            FuncionID = 22,
                            UserID = 96
                        },
                        new
                        {
                            ReservaID = 44,
                            Asiento = 41,
                            FuncionID = 12,
                            UserID = 70
                        },
                        new
                        {
                            ReservaID = 45,
                            Asiento = 25,
                            FuncionID = 18,
                            UserID = 31
                        },
                        new
                        {
                            ReservaID = 46,
                            Asiento = 13,
                            FuncionID = 23,
                            UserID = 88
                        },
                        new
                        {
                            ReservaID = 47,
                            Asiento = 39,
                            FuncionID = 1,
                            UserID = 23
                        },
                        new
                        {
                            ReservaID = 48,
                            Asiento = 2,
                            FuncionID = 4,
                            UserID = 78
                        },
                        new
                        {
                            ReservaID = 49,
                            Asiento = 17,
                            FuncionID = 8,
                            UserID = 65
                        },
                        new
                        {
                            ReservaID = 50,
                            Asiento = 42,
                            FuncionID = 5,
                            UserID = 90
                        },
                        new
                        {
                            ReservaID = 51,
                            Asiento = 20,
                            FuncionID = 7,
                            UserID = 53
                        },
                        new
                        {
                            ReservaID = 52,
                            Asiento = 31,
                            FuncionID = 10,
                            UserID = 44
                        },
                        new
                        {
                            ReservaID = 53,
                            Asiento = 14,
                            FuncionID = 13,
                            UserID = 26
                        },
                        new
                        {
                            ReservaID = 54,
                            Asiento = 48,
                            FuncionID = 16,
                            UserID = 8
                        },
                        new
                        {
                            ReservaID = 55,
                            Asiento = 37,
                            FuncionID = 19,
                            UserID = 11
                        },
                        new
                        {
                            ReservaID = 56,
                            Asiento = 23,
                            FuncionID = 21,
                            UserID = 32
                        },
                        new
                        {
                            ReservaID = 57,
                            Asiento = 12,
                            FuncionID = 24,
                            UserID = 94
                        },
                        new
                        {
                            ReservaID = 58,
                            Asiento = 29,
                            FuncionID = 2,
                            UserID = 49
                        },
                        new
                        {
                            ReservaID = 59,
                            Asiento = 7,
                            FuncionID = 14,
                            UserID = 66
                        },
                        new
                        {
                            ReservaID = 60,
                            Asiento = 50,
                            FuncionID = 17,
                            UserID = 100
                        });
                });

            modelBuilder.Entity("TeatroAPI.Model.Sala", b =>
                {
                    b.Property<int>("SalaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalaID"));

                    b.Property<int?>("Capacidad")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SalaID");

                    b.ToTable("Salas");

                    b.HasData(
                        new
                        {
                            SalaID = 1,
                            Capacidad = 100,
                            Nombre = "Sala Principal"
                        },
                        new
                        {
                            SalaID = 2,
                            Capacidad = 50,
                            Nombre = "Sala Secundaria"
                        });
                });

            modelBuilder.Entity("TeatroAPI.Model.Sesion", b =>
                {
                    b.Property<int>("SessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionID"));

                    b.Property<DateTime?>("FechaFin")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("SessionID");

                    b.HasIndex("UserID");

                    b.ToTable("Sesiones");
                });

            modelBuilder.Entity("TeatroAPI.Model.Usuario", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Apellido = "Gomez",
                            Contra = "pass01",
                            Email = "carlosgomez@mail.com",
                            Nombre = "Carlos",
                            Rol = 0,
                            Telefono = "650600001"
                        },
                        new
                        {
                            UserID = 2,
                            Apellido = "Lopez",
                            Contra = "pass02",
                            Email = "analopez@mail.com",
                            Nombre = "Ana",
                            Rol = 0,
                            Telefono = "650600002"
                        },
                        new
                        {
                            UserID = 3,
                            Apellido = "Martinez",
                            Contra = "pass03",
                            Email = "luismartinez@mail.com",
                            Nombre = "Luis",
                            Rol = 0,
                            Telefono = "650600003"
                        },
                        new
                        {
                            UserID = 4,
                            Apellido = "Hernandez",
                            Contra = "pass04",
                            Email = "sofiahernandez@mail.com",
                            Nombre = "Sofia",
                            Rol = 0,
                            Telefono = "650600004"
                        },
                        new
                        {
                            UserID = 5,
                            Apellido = "Ramirez",
                            Contra = "pass05",
                            Email = "marioramirez@mail.com",
                            Nombre = "Mario",
                            Rol = 0,
                            Telefono = "650600005"
                        },
                        new
                        {
                            UserID = 6,
                            Apellido = "Fernandez",
                            Contra = "pass06",
                            Email = "laurafernandez@mail.com",
                            Nombre = "Laura",
                            Rol = 0,
                            Telefono = "650600006"
                        },
                        new
                        {
                            UserID = 7,
                            Apellido = "Gonzalez",
                            Contra = "pass07",
                            Email = "davidgonzalez@mail.com",
                            Nombre = "David",
                            Rol = 0,
                            Telefono = "650600007"
                        },
                        new
                        {
                            UserID = 8,
                            Apellido = "Ruiz",
                            Contra = "pass08",
                            Email = "monicaruiz@mail.com",
                            Nombre = "Monica",
                            Rol = 0,
                            Telefono = "650600008"
                        },
                        new
                        {
                            UserID = 9,
                            Apellido = "Diaz",
                            Contra = "pass09",
                            Email = "jorgediaz@mail.com",
                            Nombre = "Jorge",
                            Rol = 0,
                            Telefono = "650600009"
                        },
                        new
                        {
                            UserID = 10,
                            Apellido = "Moreno",
                            Contra = "pass10",
                            Email = "carmenmoreno@mail.com",
                            Nombre = "Carmen",
                            Rol = 0,
                            Telefono = "650600010"
                        },
                        new
                        {
                            UserID = 11,
                            Apellido = "Alvarez",
                            Contra = "pass11",
                            Email = "fernandoalvarez@mail.com",
                            Nombre = "Fernando",
                            Rol = 0,
                            Telefono = "650600011"
                        },
                        new
                        {
                            UserID = 12,
                            Apellido = "Perez",
                            Contra = "pass12",
                            Email = "beatrizperez@mail.com",
                            Nombre = "Beatriz",
                            Rol = 0,
                            Telefono = "650600012"
                        },
                        new
                        {
                            UserID = 13,
                            Apellido = "Jimenez",
                            Contra = "pass13",
                            Email = "robertojimenez@mail.com",
                            Nombre = "Roberto",
                            Rol = 0,
                            Telefono = "650600013"
                        },
                        new
                        {
                            UserID = 14,
                            Apellido = "Lopez",
                            Contra = "pass14",
                            Email = "patricialopez@mail.com",
                            Nombre = "Patricia",
                            Rol = 0,
                            Telefono = "650600014"
                        },
                        new
                        {
                            UserID = 15,
                            Apellido = "Sanchez",
                            Contra = "pass15",
                            Email = "manuelsanchez@mail.com",
                            Nombre = "Manuel",
                            Rol = 0,
                            Telefono = "650600015"
                        },
                        new
                        {
                            UserID = 16,
                            Apellido = "Morales",
                            Contra = "pass16",
                            Email = "silviamorales@mail.com",
                            Nombre = "Silvia",
                            Rol = 0,
                            Telefono = "650600016"
                        },
                        new
                        {
                            UserID = 17,
                            Apellido = "Navarro",
                            Contra = "pass17",
                            Email = "oscarnavarro@mail.com",
                            Nombre = "Oscar",
                            Rol = 0,
                            Telefono = "650600017"
                        },
                        new
                        {
                            UserID = 18,
                            Apellido = "Gutierrez",
                            Contra = "pass18",
                            Email = "teresagutierrez@mail.com",
                            Nombre = "Teresa",
                            Rol = 0,
                            Telefono = "650600018"
                        },
                        new
                        {
                            UserID = 19,
                            Apellido = "Romero",
                            Contra = "pass19",
                            Email = "albertoromero@mail.com",
                            Nombre = "Alberto",
                            Rol = 0,
                            Telefono = "650600019"
                        },
                        new
                        {
                            UserID = 20,
                            Apellido = "Torres",
                            Contra = "pass20",
                            Email = "luciatorres@mail.com",
                            Nombre = "Lucia",
                            Rol = 0,
                            Telefono = "650600020"
                        },
                        new
                        {
                            UserID = 21,
                            Apellido = "Molina",
                            Contra = "pass21",
                            Email = "elenamolina@mail.com",
                            Nombre = "Elena",
                            Rol = 0,
                            Telefono = "650600021"
                        },
                        new
                        {
                            UserID = 22,
                            Apellido = "Vidal",
                            Contra = "pass22",
                            Email = "pablovidal@mail.com",
                            Nombre = "Pablo",
                            Rol = 0,
                            Telefono = "650600022"
                        },
                        new
                        {
                            UserID = 23,
                            Apellido = "Ortega",
                            Contra = "pass23",
                            Email = "sandraortega@mail.com",
                            Nombre = "Sandra",
                            Rol = 0,
                            Telefono = "650600023"
                        },
                        new
                        {
                            UserID = 24,
                            Apellido = "Pascual",
                            Contra = "pass24",
                            Email = "sergiopascual@mail.com",
                            Nombre = "Sergio",
                            Rol = 0,
                            Telefono = "650600024"
                        },
                        new
                        {
                            UserID = 25,
                            Apellido = "Ibañez",
                            Contra = "pass25",
                            Email = "raquelibanez@mail.com",
                            Nombre = "Raquel",
                            Rol = 0,
                            Telefono = "650600025"
                        },
                        new
                        {
                            UserID = 26,
                            Apellido = "Mendez",
                            Contra = "pass26",
                            Email = "juanmendez@mail.com",
                            Nombre = "Juan",
                            Rol = 0,
                            Telefono = "650600026"
                        },
                        new
                        {
                            UserID = 27,
                            Apellido = "Dominguez",
                            Contra = "pass27",
                            Email = "martadominguez@mail.com",
                            Nombre = "Marta",
                            Rol = 0,
                            Telefono = "650600027"
                        },
                        new
                        {
                            UserID = 28,
                            Apellido = "Gil",
                            Contra = "pass28",
                            Email = "antoniogil@mail.com",
                            Nombre = "Antonio",
                            Rol = 0,
                            Telefono = "650600028"
                        },
                        new
                        {
                            UserID = 29,
                            Apellido = "Vargas",
                            Contra = "pass29",
                            Email = "isabelvargas@mail.com",
                            Nombre = "Isabel",
                            Rol = 0,
                            Telefono = "650600029"
                        },
                        new
                        {
                            UserID = 30,
                            Apellido = "Blanco",
                            Contra = "pass30",
                            Email = "joseblanco@mail.com",
                            Nombre = "José",
                            Rol = 0,
                            Telefono = "650600030"
                        },
                        new
                        {
                            UserID = 31,
                            Apellido = "Santos",
                            Contra = "pass31",
                            Email = "cristinasantos@mail.com",
                            Nombre = "Cristina",
                            Rol = 0,
                            Telefono = "650600031"
                        },
                        new
                        {
                            UserID = 32,
                            Apellido = "Marin",
                            Contra = "pass32",
                            Email = "franciscomarin@mail.com",
                            Nombre = "Francisco",
                            Rol = 0,
                            Telefono = "650600032"
                        },
                        new
                        {
                            UserID = 33,
                            Apellido = "Lozano",
                            Contra = "pass33",
                            Email = "lauralozano@mail.com",
                            Nombre = "Laura",
                            Rol = 0,
                            Telefono = "650600033"
                        },
                        new
                        {
                            UserID = 34,
                            Apellido = "Sanchez",
                            Contra = "pass34",
                            Email = "victorsanchez@mail.com",
                            Nombre = "Victor",
                            Rol = 0,
                            Telefono = "650600034"
                        },
                        new
                        {
                            UserID = 35,
                            Apellido = "Garcia",
                            Contra = "pass35",
                            Email = "mariagarcia@mail.com",
                            Nombre = "Maria",
                            Rol = 0,
                            Telefono = "650600035"
                        },
                        new
                        {
                            UserID = 36,
                            Apellido = "Morales",
                            Contra = "pass36",
                            Email = "javiermorales@mail.com",
                            Nombre = "Javier",
                            Rol = 0,
                            Telefono = "650600036"
                        },
                        new
                        {
                            UserID = 37,
                            Apellido = "Herrera",
                            Contra = "pass37",
                            Email = "dianaherrera@mail.com",
                            Nombre = "Diana",
                            Rol = 0,
                            Telefono = "650600037"
                        },
                        new
                        {
                            UserID = 38,
                            Apellido = "Garrido",
                            Contra = "pass38",
                            Email = "marcosgarrido@mail.com",
                            Nombre = "Marcos",
                            Rol = 0,
                            Telefono = "650600038"
                        },
                        new
                        {
                            UserID = 39,
                            Apellido = "Priet}",
                            Contra = "pass39",
                            Email = "yolandapriet@mail.com",
                            Nombre = "Yolanda",
                            Rol = 0,
                            Telefono = "650600039"
                        },
                        new
                        {
                            UserID = 40,
                            Apellido = "Cano",
                            Contra = "pass40",
                            Email = "luiscano@mail.com",
                            Nombre = "Luis",
                            Rol = 0,
                            Telefono = "650600040"
                        },
                        new
                        {
                            UserID = 41,
                            Apellido = "Vidal",
                            Contra = "pass41",
                            Email = "danielvidal@mail.com",
                            Nombre = "Daniel",
                            Rol = 0,
                            Telefono = "650600041"
                        },
                        new
                        {
                            UserID = 42,
                            Apellido = "Moya",
                            Contra = "pass42",
                            Email = "saramoya@mail.com",
                            Nombre = "Sara",
                            Rol = 0,
                            Telefono = "650600042"
                        },
                        new
                        {
                            UserID = 43,
                            Apellido = "Ortega",
                            Contra = "pass43",
                            Email = "alexortega@mail.com",
                            Nombre = "Alex",
                            Rol = 0,
                            Telefono = "650600043"
                        },
                        new
                        {
                            UserID = 44,
                            Apellido = "Prieto",
                            Contra = "pass44",
                            Email = "marinaprieto@mail.com",
                            Nombre = "Marina",
                            Rol = 0,
                            Telefono = "650600044"
                        },
                        new
                        {
                            UserID = 45,
                            Apellido = "Mendez",
                            Contra = "pass45",
                            Email = "pablomendez@mail.com",
                            Nombre = "Pablo",
                            Rol = 0,
                            Telefono = "650600045"
                        },
                        new
                        {
                            UserID = 46,
                            Apellido = "Herrero",
                            Contra = "pass46",
                            Email = "claraherrero@mail.com",
                            Nombre = "Clara",
                            Rol = 0,
                            Telefono = "650600046"
                        },
                        new
                        {
                            UserID = 47,
                            Apellido = "Sancho",
                            Contra = "pass47",
                            Email = "ivansancho@mail.com",
                            Nombre = "Ivan",
                            Rol = 0,
                            Telefono = "650600047"
                        },
                        new
                        {
                            UserID = 48,
                            Apellido = "Domenech",
                            Contra = "pass48",
                            Email = "juliadomenech@mail.com",
                            Nombre = "Julia",
                            Rol = 0,
                            Telefono = "650600048"
                        },
                        new
                        {
                            UserID = 49,
                            Apellido = "Vega",
                            Contra = "pass49",
                            Email = "sergiovega@mail.com",
                            Nombre = "Sergio",
                            Rol = 0,
                            Telefono = "650600049"
                        },
                        new
                        {
                            UserID = 50,
                            Apellido = "Lorenzo",
                            Contra = "pass50",
                            Email = "rosalorenzo@mail.com",
                            Nombre = "Rosa",
                            Rol = 0,
                            Telefono = "650600050"
                        },
                        new
                        {
                            UserID = 51,
                            Apellido = "Costa",
                            Contra = "pass51",
                            Email = "raulcosta@mail.com",
                            Nombre = "Raul",
                            Rol = 0,
                            Telefono = "650600051"
                        },
                        new
                        {
                            UserID = 52,
                            Apellido = "Gallego",
                            Contra = "pass52",
                            Email = "elenagallego@mail.com",
                            Nombre = "Elena",
                            Rol = 0,
                            Telefono = "650600052"
                        },
                        new
                        {
                            UserID = 53,
                            Apellido = "Pascual",
                            Contra = "pass53",
                            Email = "adrianpascual@mail.com",
                            Nombre = "Adrian",
                            Rol = 0,
                            Telefono = "650600053"
                        },
                        new
                        {
                            UserID = 54,
                            Apellido = "Iglesias",
                            Contra = "pass54",
                            Email = "nuriaiglesias@mail.com",
                            Nombre = "Nuria",
                            Rol = 0,
                            Telefono = "650600054"
                        },
                        new
                        {
                            UserID = 55,
                            Apellido = "Serrano",
                            Contra = "pass55",
                            Email = "jaimeserrano@mail.com",
                            Nombre = "Jaime",
                            Rol = 0,
                            Telefono = "650600055"
                        },
                        new
                        {
                            UserID = 56,
                            Apellido = "Garrido",
                            Contra = "pass56",
                            Email = "cristinagarrido@mail.com",
                            Nombre = "Cristina",
                            Rol = 0,
                            Telefono = "650600056"
                        },
                        new
                        {
                            UserID = 57,
                            Apellido = "Merino",
                            Contra = "pass57",
                            Email = "rubenmerino@mail.com",
                            Nombre = "Ruben",
                            Rol = 0,
                            Telefono = "650600057"
                        },
                        new
                        {
                            UserID = 58,
                            Apellido = "Redondo",
                            Contra = "pass58",
                            Email = "lorenaredondo@mail.com",
                            Nombre = "Lorena",
                            Rol = 0,
                            Telefono = "650600058"
                        },
                        new
                        {
                            UserID = 59,
                            Apellido = "Molina",
                            Contra = "pass59",
                            Email = "hectormolina@mail.com",
                            Nombre = "Hector",
                            Rol = 0,
                            Telefono = "650600059"
                        },
                        new
                        {
                            UserID = 60,
                            Apellido = "Benitez",
                            Contra = "pass60",
                            Email = "martabenitez@mail.com",
                            Nombre = "Marta",
                            Rol = 0,
                            Telefono = "650600060"
                        },
                        new
                        {
                            UserID = 61,
                            Apellido = "Nieto",
                            Contra = "pass61",
                            Email = "albertnieto@mail.com",
                            Nombre = "Albert",
                            Rol = 0,
                            Telefono = "650600061"
                        },
                        new
                        {
                            UserID = 62,
                            Apellido = "Campos",
                            Contra = "pass62",
                            Email = "soniacampos@mail.com",
                            Nombre = "Sonia",
                            Rol = 0,
                            Telefono = "650600062"
                        },
                        new
                        {
                            UserID = 63,
                            Apellido = "Blanco",
                            Contra = "pass63",
                            Email = "gonzaloblanco@mail.com",
                            Nombre = "Gonzalo",
                            Rol = 0,
                            Telefono = "650600063"
                        },
                        new
                        {
                            UserID = 64,
                            Apellido = "Sanchez",
                            Contra = "pass64",
                            Email = "aliciasanchez@mail.com",
                            Nombre = "Alicia",
                            Rol = 0,
                            Telefono = "650600064"
                        },
                        new
                        {
                            UserID = 65,
                            Apellido = "Leon",
                            Contra = "pass65",
                            Email = "omarleon@mail.com",
                            Nombre = "Omar",
                            Rol = 0,
                            Telefono = "650600065"
                        },
                        new
                        {
                            UserID = 66,
                            Apellido = "Marquez",
                            Contra = "pass66",
                            Email = "lidiamarquez@mail.com",
                            Nombre = "Lidia",
                            Rol = 0,
                            Telefono = "650600066"
                        },
                        new
                        {
                            UserID = 67,
                            Apellido = "Herrera",
                            Contra = "pass67",
                            Email = "juanherrera@mail.com",
                            Nombre = "Juan",
                            Rol = 0,
                            Telefono = "650600067"
                        },
                        new
                        {
                            UserID = 68,
                            Apellido = "Cortes",
                            Contra = "pass68",
                            Email = "luciacortes@mail.com",
                            Nombre = "Lucia",
                            Rol = 0,
                            Telefono = "650600068"
                        },
                        new
                        {
                            UserID = 69,
                            Apellido = "Vidal",
                            Contra = "pass69",
                            Email = "nachovidal@mail.com",
                            Nombre = "Nacho",
                            Rol = 0,
                            Telefono = "650600069"
                        },
                        new
                        {
                            UserID = 70,
                            Apellido = "Cabrera",
                            Contra = "pass70",
                            Email = "belencabrera@mail.com",
                            Nombre = "Belen",
                            Rol = 0,
                            Telefono = "650600070"
                        },
                        new
                        {
                            UserID = 71,
                            Apellido = "Vega",
                            Contra = "pass71",
                            Email = "carlosvega@mail.com",
                            Nombre = "Carlos",
                            Rol = 0,
                            Telefono = "650600071"
                        },
                        new
                        {
                            UserID = 72,
                            Apellido = "Moreno",
                            Contra = "pass72",
                            Email = "inesmoreno@mail.com",
                            Nombre = "Ines",
                            Rol = 0,
                            Telefono = "650600072"
                        },
                        new
                        {
                            UserID = 73,
                            Apellido = "Ruiz",
                            Contra = "pass73",
                            Email = "andresruiz@mail.com",
                            Nombre = "Andres",
                            Rol = 0,
                            Telefono = "650600073"
                        },
                        new
                        {
                            UserID = 74,
                            Apellido = "Saez",
                            Contra = "pass74",
                            Email = "carmensaez@mail.com",
                            Nombre = "Carmen",
                            Rol = 0,
                            Telefono = "650600074"
                        },
                        new
                        {
                            UserID = 75,
                            Apellido = "Molina",
                            Contra = "pass75",
                            Email = "javiermolina@mail.com",
                            Nombre = "Javier",
                            Rol = 0,
                            Telefono = "650600075"
                        },
                        new
                        {
                            UserID = 76,
                            Apellido = "Herrera",
                            Contra = "pass76",
                            Email = "saraherrera@mail.com",
                            Nombre = "Sara",
                            Rol = 0,
                            Telefono = "650600076"
                        },
                        new
                        {
                            UserID = 77,
                            Apellido = "Dominguez",
                            Contra = "pass77",
                            Email = "estebandominguez@mail.com",
                            Nombre = "Esteban",
                            Rol = 0,
                            Telefono = "650600077"
                        },
                        new
                        {
                            UserID = 78,
                            Apellido = "Lopez",
                            Contra = "pass78",
                            Email = "claralopez@mail.com",
                            Nombre = "Clara",
                            Rol = 0,
                            Telefono = "650600078"
                        },
                        new
                        {
                            UserID = 79,
                            Apellido = "Garcia",
                            Contra = "pass79",
                            Email = "rubengarcia@mail.com",
                            Nombre = "Ruben",
                            Rol = 0,
                            Telefono = "650600079"
                        },
                        new
                        {
                            UserID = 80,
                            Apellido = "Fernandez",
                            Contra = "pass80",
                            Email = "martafernandez@mail.com",
                            Nombre = "Marta",
                            Rol = 0,
                            Telefono = "650600080"
                        },
                        new
                        {
                            UserID = 81,
                            Apellido = "Gomez",
                            Contra = "pass81",
                            Email = "luisgomez@mail.com",
                            Nombre = "Luis",
                            Rol = 0,
                            Telefono = "650600081"
                        },
                        new
                        {
                            UserID = 82,
                            Apellido = "Martinez",
                            Contra = "pass82",
                            Email = "anamartinez@mail.com",
                            Nombre = "Ana",
                            Rol = 0,
                            Telefono = "650600082"
                        },
                        new
                        {
                            UserID = 83,
                            Apellido = "Jimenez",
                            Contra = "pass83",
                            Email = "davidjimenez@mail.com",
                            Nombre = "David",
                            Rol = 0,
                            Telefono = "650600083"
                        },
                        new
                        {
                            UserID = 84,
                            Apellido = "Sanchez",
                            Contra = "pass84",
                            Email = "patriciasanchez@mail.com",
                            Nombre = "Patricia",
                            Rol = 0,
                            Telefono = "650600084"
                        },
                        new
                        {
                            UserID = 85,
                            Apellido = "Lorenzo",
                            Contra = "pass85",
                            Email = "oscarlorenzo@mail.com",
                            Nombre = "Oscar",
                            Rol = 0,
                            Telefono = "650600085"
                        },
                        new
                        {
                            UserID = 86,
                            Apellido = "Mora",
                            Contra = "pass86",
                            Email = "lauramora@mail.com",
                            Nombre = "Laura",
                            Rol = 0,
                            Telefono = "650600086"
                        },
                        new
                        {
                            UserID = 87,
                            Apellido = "Alonso",
                            Contra = "pass87",
                            Email = "ivanalonso@mail.com",
                            Nombre = "Ivan",
                            Rol = 0,
                            Telefono = "650600087"
                        },
                        new
                        {
                            UserID = 88,
                            Apellido = "Vidal",
                            Contra = "pass88",
                            Email = "monicavidal@mail.com",
                            Nombre = "Monica",
                            Rol = 0,
                            Telefono = "650600088"
                        },
                        new
                        {
                            UserID = 89,
                            Apellido = "Prieto",
                            Contra = "pass89",
                            Email = "jorgeprieto@mail.com",
                            Nombre = "Jorge",
                            Rol = 0,
                            Telefono = "650600089"
                        },
                        new
                        {
                            UserID = 90,
                            Apellido = "Campos",
                            Contra = "pass90",
                            Email = "teresacampos@mail.com",
                            Nombre = "Teresa",
                            Rol = 0,
                            Telefono = "650600090"
                        },
                        new
                        {
                            UserID = 91,
                            Apellido = "Gil",
                            Contra = "pass91",
                            Email = "manuelgil@mail.com",
                            Nombre = "Manuel",
                            Rol = 0,
                            Telefono = "650600091"
                        },
                        new
                        {
                            UserID = 92,
                            Apellido = "Mendez",
                            Contra = "pass92",
                            Email = "silviamendez@mail.com",
                            Nombre = "Silvia",
                            Rol = 0,
                            Telefono = "650600092"
                        },
                        new
                        {
                            UserID = 93,
                            Apellido = "Herrero",
                            Contra = "pass93",
                            Email = "antonioherrero@mail.com",
                            Nombre = "Antonio",
                            Rol = 0,
                            Telefono = "650600093"
                        },
                        new
                        {
                            UserID = 94,
                            Apellido = "Sancho",
                            Contra = "pass94",
                            Email = "luciasancho@mail.com",
                            Nombre = "Lucia",
                            Rol = 0,
                            Telefono = "650600094"
                        },
                        new
                        {
                            UserID = 95,
                            Apellido = "Dominguez",
                            Contra = "pass95",
                            Email = "migueldominguez@mail.com",
                            Nombre = "Miguel",
                            Rol = 0,
                            Telefono = "650600095"
                        },
                        new
                        {
                            UserID = 96,
                            Apellido = "Vega",
                            Contra = "pass96",
                            Email = "nuriavega@mail.com",
                            Nombre = "Nuria",
                            Rol = 0,
                            Telefono = "650600096"
                        },
                        new
                        {
                            UserID = 97,
                            Apellido = "Cabrera",
                            Contra = "pass97",
                            Email = "albertocabrera@mail.com",
                            Nombre = "Alberto",
                            Rol = 0,
                            Telefono = "650600097"
                        },
                        new
                        {
                            UserID = 98,
                            Apellido = "Lorenzo",
                            Contra = "pass98",
                            Email = "rociolorenzo@mail.com",
                            Nombre = "Rocio",
                            Rol = 0,
                            Telefono = "650600098"
                        },
                        new
                        {
                            UserID = 99,
                            Apellido = "Sanchez",
                            Contra = "pass99",
                            Email = "felipesanchez@mail.com",
                            Nombre = "Felipe",
                            Rol = 0,
                            Telefono = "650600099"
                        },
                        new
                        {
                            UserID = 100,
                            Apellido = "Morales",
                            Contra = "pass100",
                            Email = "beatrizmorales@mail.com",
                            Nombre = "Beatriz",
                            Rol = 0,
                            Telefono = "650600100"
                        });
                });

            modelBuilder.Entity("TeatroAPI.Model.Funcion", b =>
                {
                    b.HasOne("TeatroAPI.Model.Obra", "Obra")
                        .WithMany("Funciones")
                        .HasForeignKey("ObraID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeatroAPI.Model.Sala", "Sala")
                        .WithMany("Funciones")
                        .HasForeignKey("SalaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obra");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("TeatroAPI.Model.Reserva", b =>
                {
                    b.HasOne("TeatroAPI.Model.Funcion", "Funcion")
                        .WithMany("Reservas")
                        .HasForeignKey("FuncionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeatroAPI.Model.Usuario", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TeatroAPI.Model.Sesion", b =>
                {
                    b.HasOne("TeatroAPI.Model.Usuario", "Usuario")
                        .WithMany("Sesiones")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TeatroAPI.Model.Funcion", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("TeatroAPI.Model.Obra", b =>
                {
                    b.Navigation("Funciones");
                });

            modelBuilder.Entity("TeatroAPI.Model.Sala", b =>
                {
                    b.Navigation("Funciones");
                });

            modelBuilder.Entity("TeatroAPI.Model.Usuario", b =>
                {
                    b.Navigation("Reservas");

                    b.Navigation("Sesiones");
                });
#pragma warning restore 612, 618
        }
    }
}
