// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeatroAPI.Data;

#nullable disable

namespace TeatroAPI.Data.Migrations
{
    [DbContext(typeof(TeatroAPIContext))]
    [Migration("20240228161905_MigracionInicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeatroAPI.Model.Funcion", b =>
                {
                    b.Property<int>("FuncionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FuncionID"));

                    b.Property<DateTime?>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ObraID")
                        .HasColumnType("int");

                    b.Property<int?>("Precio")
                        .HasColumnType("int");

                    b.Property<int?>("SalaID")
                        .HasColumnType("int");

                    b.HasKey("FuncionID");

                    b.HasIndex("ObraID");

                    b.HasIndex("SalaID");

                    b.ToTable("Funciones");

                    b.HasData(
                        new
                        {
                            FuncionID = 1,
                            FechaHora = new DateTime(2024, 3, 15, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            ObraID = 1,
                            SalaID = 1
                        },
                        new
                        {
                            FuncionID = 2,
                            FechaHora = new DateTime(2024, 3, 16, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            ObraID = 2,
                            SalaID = 2
                        },
                        new
                        {
                            FuncionID = 3,
                            FechaHora = new DateTime(2024, 3, 17, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            ObraID = 1,
                            SalaID = 1
                        });
                });

            modelBuilder.Entity("TeatroAPI.Model.Obra", b =>
                {
                    b.Property<int>("ObraID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObraID"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ObraID");

                    b.ToTable("Obras");

                    b.HasData(
                        new
                        {
                            ObraID = 1,
                            Director = "Pedro Calderón de la Barca",
                            Titulo = "La vida es sueño"
                        },
                        new
                        {
                            ObraID = 2,
                            Director = "William Shakespeare",
                            Titulo = "Hamlet"
                        });
                });

            modelBuilder.Entity("TeatroAPI.Model.Reserva", b =>
                {
                    b.Property<int>("ReservaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservaID"));

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("datetime2");

                    b.Property<int>("FuncionID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ReservaID");

                    b.HasIndex("FuncionID");

                    b.HasIndex("UserID");

                    b.ToTable("Reservas");

                    b.HasData(
                        new
                        {
                            ReservaID = 1,
                            FechaReserva = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuncionID = 1,
                            UserID = 1
                        },
                        new
                        {
                            ReservaID = 2,
                            FechaReserva = new DateTime(2024, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuncionID = 2,
                            UserID = 2
                        },
                        new
                        {
                            ReservaID = 3,
                            FechaReserva = new DateTime(2024, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuncionID = 3,
                            UserID = 1
                        });
                });

            modelBuilder.Entity("TeatroAPI.Model.Sala", b =>
                {
                    b.Property<int>("SalaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalaID"));

                    b.Property<int?>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SalaID");

                    b.ToTable("Salas");

                    b.HasData(
                        new
                        {
                            SalaID = 1,
                            Capacidad = 100,
                            Nombre = "Sala Principal"
                        },
                        new
                        {
                            SalaID = 2,
                            Capacidad = 50,
                            Nombre = "Sala Secundaria"
                        });
                });

            modelBuilder.Entity("TeatroAPI.Model.Sesion", b =>
                {
                    b.Property<int>("SessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionID"));

                    b.Property<string>("Dispositivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("SessionID");

                    b.HasIndex("UserID");

                    b.ToTable("Sesiones");
                });

            modelBuilder.Entity("TeatroAPI.Model.Usuario", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Email = "juanperez@mail.com",
                            Nombre = "Juan Pérez",
                            Rol = 0
                        },
                        new
                        {
                            UserID = 2,
                            Email = "analopez@mail.com",
                            Nombre = "Ana López",
                            Rol = 0
                        });
                });

            modelBuilder.Entity("TeatroAPI.Model.Funcion", b =>
                {
                    b.HasOne("TeatroAPI.Model.Obra", "Obra")
                        .WithMany("Funciones")
                        .HasForeignKey("ObraID");

                    b.HasOne("TeatroAPI.Model.Sala", "Sala")
                        .WithMany("Funciones")
                        .HasForeignKey("SalaID");

                    b.Navigation("Obra");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("TeatroAPI.Model.Reserva", b =>
                {
                    b.HasOne("TeatroAPI.Model.Funcion", "Funcion")
                        .WithMany("Reservas")
                        .HasForeignKey("FuncionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeatroAPI.Model.Usuario", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TeatroAPI.Model.Sesion", b =>
                {
                    b.HasOne("TeatroAPI.Model.Usuario", "Usuario")
                        .WithMany("Sesiones")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TeatroAPI.Model.Funcion", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("TeatroAPI.Model.Obra", b =>
                {
                    b.Navigation("Funciones");
                });

            modelBuilder.Entity("TeatroAPI.Model.Sala", b =>
                {
                    b.Navigation("Funciones");
                });

            modelBuilder.Entity("TeatroAPI.Model.Usuario", b =>
                {
                    b.Navigation("Reservas");

                    b.Navigation("Sesiones");
                });
#pragma warning restore 612, 618
        }
    }
}
