apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver-deplo
  labels:
    env: db
spec:
  replicas: 1
  selector:
    matchLabels:
      env: db
  template:
    metadata:
      labels:
        env: db
    spec:
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2019-latest
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "ContraFuerteParaOmarhOO123!!"
          ports:
            - containerPort: 1433
          volumeMounts:
            - name: sqlserver-storage
              mountPath: /var/opt/mssql/data
      volumes:
        - name: sqlserver-storage
          emptyDir: {}
