name: Kubernetes Backend

on:
  push:
    branches: ["main"]
env:
  ECR_REPOSITORY:
  EKS_CLUSTER_NAME: teatro
  AWS_REGION: us-east-1

jobs:
  build:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Set short git commit SHA
        id: commit
        uses: prompt/actions-commit-hash@v2

      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kube config
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

      - name: Deploy to EKS
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 905418170343.dkr.ecr.us-east-1.amazonaws.com
          docker build -t teatroapi:${{ steps.commit.outputs.short }} .
          docker tag teatroapi:${{ steps.commit.outputs.short }} 905418170343.dkr.ecr.us-east-1.amazonaws.com/teatroapi:${{ steps.commit.outputs.short }}
          docker push 905418170343.dkr.ecr.us-east-1.amazonaws.com/teatroapi:${{ steps.commit.outputs.short }}
          sed -i "s|905418170343.dkr.ecr.us-east-1.amazonaws.com/teatroapi|905418170343.dkr.ecr.us-east-1.amazonaws.com/teatroapi:${{ steps.commit.outputs.short }}|" kubernetes/api-deployment.yaml
          kubectl apply -f kubernetes/api-deployment.yaml
          kubectl apply -f kubernetes/api-svc.yaml

      - name: Echo commit SHA
        run: echo ${{ steps.commit.outputs.short }}

      - name: Check the modified api-deployment.yaml
        run: cat kubernetes/api-deployment.yaml
